import React from "react";
import prisma from "@/lib/prisma";
import { getCurrentUser } from "@/lib/auth";
import { redirect } from "next/navigation";
import { User, Mail, ShieldAlert, Award, Calendar, Landmark, MapPin, Receipt, ArrowRight, ReceiptCent } from "lucide-react";

export const revalidate = 0; // Fresh details each load

export default async function ProfilePage() {
  const session = await getCurrentUser();
  if (!session) {
    redirect("/login");
  }

  // Fetch full user records from DB, including branch mappings
  const user = await prisma.user.findUnique({
    where: { id: session.userId },
    include: {
      branch: {
        select: {
          id: true,
          name: true,
          street: true,
          city: true
        }
      }
    }
  });

  if (!user) {
    return (
      <div className="p-8 max-w-4xl mx-auto mt-12 bg-zinc-900 border border-zinc-800 rounded-2xl">
        <h2 className="text-2xl font-bold text-red-500 mb-2">Error</h2>
        <p className="text-zinc-400">User profile record could not be loaded.</p>
      </div>
    );
  }

  // Query all invoices billed/generated by this user
  const invoices = await prisma.invoice.findMany({
    where: {
      billedById: user.id,
      delete: false
    },
    orderBy: {
      createdAt: "desc"
    },
    include: {
      branch: {
        select: { name: true }
      }
    }
  });

  // Calculate metrics
  const totalBills = invoices.length;
  const totalSalesRevenue = invoices.reduce((sum, inv) => sum + inv.total, 0);
  const avgSalesValue = totalBills > 0 ? totalSalesRevenue / totalBills : 0;

  return (
    <div className="p-6 md:p-8 space-y-8 max-w-6xl mx-auto select-none">
      
      {/* Title Header */}
      <div className="border-b border-zinc-800/80 pb-6 flex items-center gap-3">
        <div className="p-2.5 bg-amber-500/10 rounded-xl text-amber-500">
          <User className="w-8 h-8" />
        </div>
        <div>
          <h1 className="text-3xl font-extrabold tracking-tight text-white">My Account Profile</h1>
          <p className="text-zinc-400 text-sm mt-1">
            Manage your credentials, verify branch allocations, and track your logged transaction volumes.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Left Side: Profile Details */}
        <div className="space-y-6 lg:col-span-1">
          <div className="bg-zinc-900 border border-zinc-850 rounded-2xl p-6 relative overflow-hidden group">
            {/* Ambient gold glow */}
            <div className="absolute -top-10 -right-10 w-24 h-24 rounded-full bg-amber-500/5 blur-2xl group-hover:bg-amber-500/10 transition-all duration-300"></div>
            
            <div className="flex flex-col items-center text-center pb-5 border-b border-zinc-850">
              <div className="w-16 h-16 rounded-2xl bg-zinc-950 border border-zinc-800 flex items-center justify-center text-amber-500 mb-4 shadow-inner">
                <User className="w-8 h-8" />
              </div>
              <h2 className="text-lg font-black text-white">{user.name}</h2>
              <span className={`mt-1.5 px-3 py-0.5 rounded-full text-[10px] font-black uppercase tracking-wider border ${
                user.role === "ADMIN" 
                  ? "bg-red-500/10 border-red-500/20 text-red-400"
                  : user.role === "MANAGER"
                    ? "bg-amber-500/10 border-amber-500/20 text-amber-500"
                    : "bg-blue-500/10 border-blue-500/20 text-blue-400"
              }`}>
                {user.role}
              </span>
            </div>

            {/* Profile fields */}
            <div className="pt-5 space-y-4 text-xs">
              <div className="flex items-center gap-3">
                <Mail className="w-4 h-4 text-zinc-550 shrink-0" />
                <div className="min-w-0">
                  <span className="text-[9px] text-zinc-500 uppercase font-bold block">Email Address</span>
                  <span className="text-zinc-200 font-mono break-all">{user.email}</span>
                </div>
              </div>

              <div className="flex items-center gap-3">
                <MapPin className="w-4 h-4 text-zinc-550 shrink-0" />
                <div>
                  <span className="text-[9px] text-zinc-500 uppercase font-bold block">Assigned Branch</span>
                  <span className="text-zinc-200 font-semibold">{user.branch?.name || "Global / Unassigned"}</span>
                </div>
              </div>

              {user.phone && (
                <div className="flex items-center gap-3">
                  <Landmark className="w-4 h-4 text-zinc-550 shrink-0" />
                  <div>
                    <span className="text-[9px] text-zinc-500 uppercase font-bold block">Contact Phone</span>
                    <span className="text-zinc-200 font-semibold">{user.phone}</span>
                  </div>
                </div>
              )}

              <div className="flex items-center gap-3">
                <Calendar className="w-4 h-4 text-zinc-550 shrink-0" />
                <div>
                  <span className="text-[9px] text-zinc-500 uppercase font-bold block">Registration Date</span>
                  <span className="text-zinc-200 font-semibold">{new Date(user.createdAt).toLocaleDateString([], { month: 'long', day: 'numeric', year: 'numeric' })}</span>
                </div>
              </div>
            </div>
          </div>
          
          {/* User Status details */}
          <div className="p-4 bg-zinc-900/40 border border-zinc-850/60 rounded-2xl flex items-start gap-3">
            <Award className="w-5 h-5 text-amber-500 shrink-0 mt-0.5" />
            <div className="text-xs">
              <h4 className="font-bold text-white">System Security Note</h4>
              <p className="text-zinc-450 mt-1 leading-relaxed">
                Your role credentials dictate access permissions. If you need branch assignment changes or credentials updates, contact your lead system administrator.
              </p>
            </div>
          </div>
        </div>

        {/* Right Side: Sales Metrics & Invoice List */}
        <div className="space-y-6 lg:col-span-2">
          
          {/* Cashier Stats Cards */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-5">
            <div className="bg-zinc-900 border border-zinc-850 rounded-2xl p-5">
              <span className="text-[9px] font-bold text-zinc-500 uppercase block tracking-wider">Invoices Handled</span>
              <span className="text-2xl font-black text-white block mt-2">{totalBills}</span>
              <span className="text-[10px] text-zinc-550 block mt-1">Total receipts generated</span>
            </div>

            <div className="bg-zinc-900 border border-zinc-850 rounded-2xl p-5">
              <span className="text-[9px] font-bold text-zinc-500 uppercase block tracking-wider">Gross Billed Value</span>
              <span className="text-2xl font-black text-amber-500 block mt-2">₹{Math.round(totalSalesRevenue).toLocaleString()}</span>
              <span className="text-[10px] text-zinc-550 block mt-1">Sales logged to database</span>
            </div>

            <div className="bg-zinc-900 border border-zinc-850 rounded-2xl p-5">
              <span className="text-[9px] font-bold text-zinc-500 uppercase block tracking-wider">Average Ticket</span>
              <span className="text-2xl font-black text-emerald-450 block mt-2">₹{Math.round(avgSalesValue).toLocaleString()}</span>
              <span className="text-[10px] text-zinc-550 block mt-1">Value per transaction</span>
            </div>
          </div>

          {/* Invoices List */}
          <div className="bg-zinc-900 border border-zinc-850 rounded-2xl overflow-hidden">
            <div className="px-6 py-4 bg-zinc-950/20 border-b border-zinc-850 flex items-center justify-between">
              <h3 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
                <Receipt className="w-4.5 h-4.5 text-amber-500" />
                <span>My Transaction History</span>
              </h3>
            </div>
            
            <div className="max-h-[300px] overflow-y-auto scrollbar-thin">
              {invoices.length === 0 ? (
                <div className="text-center py-16 text-zinc-500 text-xs">
                  No invoices generated by you yet.
                </div>
              ) : (
                <div className="divide-y divide-zinc-850 text-xs">
                  {invoices.map((inv) => (
                    <div key={inv.id} className="p-4 hover:bg-zinc-800/10 transition-colors flex items-center justify-between gap-4">
                      <div>
                        <div className="font-mono font-bold text-white uppercase text-[11px]">{inv.invoiceId}</div>
                        <div className="flex items-center gap-2 mt-1 text-[10px] text-zinc-500">
                          <span>{new Date(inv.createdAt).toLocaleDateString()}</span>
                          <span>•</span>
                          <span>{inv.branch.name}</span>
                        </div>
                      </div>
                      
                      <div className="text-right">
                        <div className="font-black text-amber-500">₹{inv.total.toFixed(2)}</div>
                        <span className="inline-flex px-1.5 py-0.5 bg-zinc-950 text-[9px] text-zinc-400 border border-zinc-850 rounded font-semibold uppercase mt-1">
                          {inv.paymentMode}
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>

        </div>

      </div>

    </div>
  );
}
